CREATE DATABASE fag_api_system;

USE DATABASE fag_api_system;

CREATE TABLE USUARIO(
    USUARIO_ID INT PRIMARY KEY AUTO_INCREMENT,
    USUARIO_SAGRES VARCHAR(30) NOT NULL,
    USUARIO_SENHA VARCHAR(32) NOT NULL
);

CREATE TABLE FORMULARIO(
    FORM_ID INT PRIMARY KEY AUTO_INCREMENT,
    FORM_DEPARTAMENTO VARCHAR(30) NOT NULL,
    FORM_FORMULARIO JSON NOT NULL
);

CREATE TABLE ALTERACAO(
    ALT_ID INT PRIMARY KEY AUTO_INCREMENT,
    ALT_TIPO VARCHAR(30) NOT NULL
);

CREATE TABLE ALTER_USUARIO_FORM(
    ALT_USUARIO INT,
    ALT_FORMULARIO INT,
    ALT_ALTERACAO INT
);

ALTER TABLE ALTER_USUARIO_FORM ADD CONSTRAINT
PRIMARY KEY (ALT_USUARIO, ALT_FORMULARIO, ALT_ALTERACAO);


INSERT INTO USUARIO VALUES(NULL,'luiz',md5('123456'));
INSERT INTO USUARIO VALUES(NULL,'mateus',md5('123456'));
INSERT INTO USUARIO VALUES(NULL,'joao',md5('123456'));
INSERT INTO USUARIO VALUES(NULL,'luana',md5('123456'));
INSERT INTO USUARIO VALUES(NULL,'matd',md5('123456'));
INSERT INTO USUARIO VALUES(NULL,'acerola',md5('123456'));
INSERT INTO USUARIO VALUES(NULL,'bruno',md5('123456'));

INSERT INTO FORMULARIO VALUES(NULL,'Engenharia de Software','{"nome" : "nome", "asdasd": "asdasd"}');
INSERT INTO FORMULARIO VALUES(NULL,'Engenharia Mecanica','{"nome" : "nome", "asdasd": "asdasd"}');
INSERT INTO FORMULARIO VALUES(NULL,'Engenharia Eletrica','{"nome" : "nome", "asdasd": "asdasd"}');
INSERT INTO FORMULARIO VALUES(NULL,'Contabeis','{"nome" : "nome", "asdasd": "asdasd"}');
INSERT INTO FORMULARIO VALUES(NULL,'Agronomia','{"nome" : "nome", "asdasd": "asdasd"}');
INSERT INTO FORMULARIO VALUES(NULL,'Enfermagem','{"nome" : "nome", "asdasd": "asdasd"}');
INSERT INTO FORMULARIO VALUES(NULL,'Engenharia de Software','{"nome" : "nome", "asdasd": "asdasd"}');
INSERT INTO FORMULARIO VALUES(NULL,'Engenharia de Software','{"nome" : "nome", "asdasd": "asdasd"}');
INSERT INTO FORMULARIO VALUES(NULL,'Engenharia de Software','{"nome" : "nome", "asdasd": "asdasd"}');
INSERT INTO FORMULARIO VALUES(NULL,'Medicina','{"nome" : "nome", "asdasd": "asdasd"}');


INSERT INTO ALTERACAO VALUES(NULL,'RESPONDIDO');
INSERT INTO ALTERACAO VALUES(NULL,'VISUALIZADO');

INSERT INTO ALTER_USUARIO_FORM VALUES(1,1,1);
INSERT INTO ALTER_USUARIO_FORM VALUES(1,1,2);
INSERT INTO ALTER_USUARIO_FORM VALUES(2,2,1);
INSERT INTO ALTER_USUARIO_FORM VALUES(3,2,2);
INSERT INTO ALTER_USUARIO_FORM VALUES(3,3,1);
INSERT INTO ALTER_USUARIO_FORM VALUES(3,3,2);
INSERT INTO ALTER_USUARIO_FORM VALUES(4,4,1);
INSERT INTO ALTER_USUARIO_FORM VALUES(5,5,1);
INSERT INTO ALTER_USUARIO_FORM VALUES(6,6,1);
INSERT INTO ALTER_USUARIO_FORM VALUES(7,7,1);
INSERT INTO ALTER_USUARIO_FORM VALUES(4,8,1);
INSERT INTO ALTER_USUARIO_FORM VALUES(4,8,2);
INSERT INTO ALTER_USUARIO_FORM VALUES(2,9,1);
INSERT INTO ALTER_USUARIO_FORM VALUES(3,9,2);


/*VISUALIZANDO USUARIOS*/
/*SELECT USUARIO_ID, USUARIO_SAGRES, USUARIO_SENHA FROM USUARIO;

/*VISUALIZADO FORMULARIOS*/
/*SELECT FORM_ID, FORM_DEPARTAMENTO, FORM_FORMULARIO 
FROM FORMULARIO;

/*VISUALIZANDO QTD DE FORMULARIOS RESPONDIDOS POR USUARIO*/
/*SELECT USUARIO_SAGRES, COUNT(*) AS "FORMULARIOS RESPONDIDOS"
FROM USUARIO
INNER JOIN ALTER_USUARIO_FORM ON USUARIO_ID = ALT_USUARIO
WHERE ALT_ALTERACAO = 2
GROUP BY USUARIO_ID
ORDER BY 2 DESC;

/*VISUALIZANDO QTD DE FORMULARIOS VISUALIZADOS POR USUARIO*/
/*SELECT USUARIO_SAGRES, COUNT(*) AS "FORMULARIOS VISUALIZADOS"
FROM USUARIO
INNER JOIN ALTER_USUARIO_FORM ON USUARIO_ID = ALT_USUARIO
WHERE ALT_ALTERACAO = 1
GROUP BY USUARIO_ID
ORDER BY 2 DESC;

/*VISUALIZANDO FORMULARIOS QUE FORAM RESPONDIDOS*/
/*SELECT FORM_ID, FORM_DEPARTAMENTO
FROM FORMULARIO
INNER JOIN ALTER_USUARIO_FORM ON FORM_ID = ALT_FORMULARIO
WHERE ALT_ALTERACAO = 2;

/*VISUALIZANDO FORMULARIOS QUE FORAM VISUALIZADOS*/
/*SELECT FORM_ID, FORM_DEPARTAMENTO
FROM FORMULARIO
INNER JOIN ALTER_USUARIO_FORM ON FORM_ID = ALT_FORMULARIO
WHERE ALT_ALTERACAO = 1;

/*VISUALIZANDO QUEM RESPONDEU CADA FORMULARIO*/
/*SELECT USUARIO_ID, USUARIO_SAGRES, ALT_FORMULARIO
FROM USUARIO
INNER JOIN ALTER_USUARIO_FORM ON USUARIO_ID = ALT_USUARIO
WHERE ALT_ALTERACAO = 2;

/*VISUALIZANDO QUEM VISUALIZOU CADA FORMULARIO*/
/*SELECT USUARIO_ID, USUARIO_SAGRES, ALT_FORMULARIO
FROM USUARIO
INNER JOIN ALTER_USUARIO_FORM ON USUARIO_ID = ALT_USUARIO
WHERE ALT_ALTERACAO = 1;

